"""
Template Synthesizer — Response Assembly Engine
════════════════════════════════════════════════
Assembles solver outputs and retrieved knowledge into
coherent, well-structured natural language responses.

No neural network — uses rule-based template composition
with domain-specific formatting, adaptive verbosity,
and coherence scoring.
"""

import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class SynthesisContext:
    """All inputs to the synthesizer."""
    prompt: str = ""
    intent: str = "general"
    solver_answer: str = ""
    solver_confidence: float = 0.0
    solver_name: str = ""
    retrieved_passages: List[str] = field(default_factory=list)
    retrieved_scores: List[float] = field(default_factory=list)
    reasoning_trace: List[str] = field(default_factory=list)


class TemplateSynthesizer:
    """
    Assembles algorithmic solver outputs into coherent responses.

    Strategy:
      1. If solver produced a high-confidence answer → format and return
      2. If retrieval found relevant knowledge → synthesize from passages
      3. Mix both for enriched responses
      4. Fall back to structured acknowledgment
    """

    # Domain-specific response templates
    _RESPONSE_TEMPLATES = {
        "math": (
            "{solver_answer}\n\n"
            "---\n"
            "*Computed by the Cognitive Core Engine (deterministic, zero-hallucination).*"
        ),
        "code": (
            "{solver_answer}\n\n"
            "---\n"
            "*Generated by the Cognitive Core Engine — pattern-matched and template-verified.*"
        ),
        "logic": (
            "{solver_answer}\n\n"
            "---\n"
            "*Derived using formal logic (forward/backward chaining). "
            "This answer is provably correct within the given premises.*"
        ),
        "extraction": "{solver_answer}",
        "plan": (
            "{solver_answer}\n\n"
            "---\n"
            "*Plan generated by task decomposition analysis.*"
        ),
        "general": (
            "{combined_answer}\n\n"
            "---\n"
            "*Response assembled from knowledge retrieval (BM25) and algorithmic analysis.*"
        ),
        "verification": (
            "{solver_answer}"
        ),
    }

    def __init__(self):
        self._total_syntheses = 0

    def synthesize(self, context: SynthesisContext) -> str:
        """Synthesize a response from solver output and retrieved knowledge."""
        self._total_syntheses += 1

        # Strategy 1: High-confidence solver answer
        if context.solver_confidence >= 0.70 and context.solver_answer:
            template = self._RESPONSE_TEMPLATES.get(
                context.intent, self._RESPONSE_TEMPLATES["general"]
            )
            return template.format(
                solver_answer=context.solver_answer,
                combined_answer=context.solver_answer,
            )

        # Strategy 2: Combine solver + retrieval
        if context.solver_answer and context.retrieved_passages:
            return self._combine_solver_and_retrieval(context)

        # Strategy 3: Retrieval-only response
        if context.retrieved_passages:
            return self._retrieval_response(context)

        # Strategy 4: Solver-only with low confidence
        if context.solver_answer:
            return context.solver_answer

        # Strategy 5: Structured fallback
        return self._structured_fallback(context)

    def _combine_solver_and_retrieval(self, context: SynthesisContext) -> str:
        """Combine solver output with retrieved knowledge."""
        sections = []

        # Main answer from solver
        sections.append(context.solver_answer)

        # Enrichment from retrieval
        relevant = self._select_best_passages(
            context.retrieved_passages,
            context.retrieved_scores,
            max_passages=3,
        )

        if relevant:
            sections.append("\n### Additional Context\n")
            for passage, score in relevant:
                # Clean and format the passage
                cleaned = self._clean_passage(passage)
                if cleaned:
                    sections.append(f"- {cleaned}")

        return "\n".join(sections)

    def _retrieval_response(self, context: SynthesisContext) -> str:
        """Build a response purely from retrieved knowledge."""
        relevant = self._select_best_passages(
            context.retrieved_passages,
            context.retrieved_scores,
            max_passages=5,
        )

        if not relevant:
            return self._structured_fallback(context)

        # Detect if this is a question
        is_question = context.prompt.strip().endswith('?') or any(
            context.prompt.lower().startswith(q) for q in
            ['what', 'how', 'why', 'when', 'where', 'who', 'which', 'is ', 'can ', 'does ']
        )

        sections = []
        if is_question:
            sections.append(f"Based on the available knowledge:\n")
        else:
            sections.append(f"Here's what I found:\n")

        for passage, score in relevant:
            cleaned = self._clean_passage(passage)
            if cleaned:
                # Format as a paragraph if long, bullet if short
                if len(cleaned) > 200:
                    sections.append(f"{cleaned}\n")
                else:
                    sections.append(f"• {cleaned}")

        sections.append(
            "\n---\n"
            "*Retrieved from local knowledge base (BM25 scoring, "
            f"{len(relevant)} relevant passages found).*"
        )

        return "\n".join(sections)

    @staticmethod
    def _structured_fallback(context: SynthesisContext) -> str:
        """Generate a structured acknowledgment when no solver succeeds."""
        prompt_summary = context.prompt[:200].strip()

        # Try to provide something useful based on intent
        if context.intent == "code":
            return (
                f"I understand you're asking about code: \"{prompt_summary}\"\n\n"
                f"While I don't have a pre-built template for this exact pattern, "
                f"here's how I'd approach it:\n\n"
                f"1. **Identify the core algorithm** — what data structure or pattern fits?\n"
                f"2. **Define the interface** — what inputs/outputs are needed?\n"
                f"3. **Implement iteratively** — start with a simple version, then optimize\n"
                f"4. **Test with edge cases** — empty inputs, large inputs, duplicates\n\n"
                f"Try rephrasing with a specific algorithm name (e.g., 'binary search', "
                f"'merge sort', 'linked list') for a complete implementation."
            )
        elif context.intent == "math":
            return (
                f"I received your math question: \"{prompt_summary}\"\n\n"
                f"I can solve:\n"
                f"- Arithmetic expressions (e.g., '15 * 23 + 7')\n"
                f"- Statistics (mean, median, std of number sets)\n"
                f"- Linear equations (e.g., '3x + 5 = 20')\n"
                f"- Number theory (primes, factorial, fibonacci)\n\n"
                f"Try rephrasing with a clear mathematical expression."
            )
        else:
            return (
                f"I processed your request: \"{prompt_summary}\"\n\n"
                f"The Cognitive Core Engine analyzed this using:\n"
                f"- Knowledge retrieval (BM25 search)\n"
                f"- Algorithmic solvers (math, code, logic)\n"
                f"- Pattern matching and template synthesis\n\n"
                f"For more precise results, try:\n"
                f"- Asking a specific mathematical question\n"
                f"- Requesting a specific algorithm implementation\n"
                f"- Asking about a known concept or pattern"
            )

    @staticmethod
    def _select_best_passages(
        passages: List[str],
        scores: List[float],
        max_passages: int = 5,
    ) -> List[tuple]:
        """Select the best passages, filtering low-quality ones."""
        paired = list(zip(passages, scores))
        # Filter: score must be above threshold
        threshold = max(s for _, s in paired) * 0.3 if paired else 0
        filtered = [(p, s) for p, s in paired if s >= threshold and len(p.strip()) > 20]
        return filtered[:max_passages]

    @staticmethod
    def _clean_passage(passage: str) -> str:
        """Clean a passage for inclusion in a response."""
        # Remove excessive whitespace
        cleaned = re.sub(r'\n{3,}', '\n\n', passage.strip())
        # Truncate if too long
        if len(cleaned) > 500:
            # Try to cut at a sentence boundary
            cut_point = cleaned[:500].rfind('.')
            if cut_point > 200:
                cleaned = cleaned[:cut_point + 1]
            else:
                cleaned = cleaned[:500] + "..."
        return cleaned

    def get_stats(self) -> Dict[str, Any]:
        return {"total_syntheses": self._total_syntheses}
