import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
    X, Github, Download, Package, Shield, CheckCircle2, XCircle,
    Loader2, AlertTriangle, Smartphone, Globe, Gamepad2, Zap, Key
} from 'lucide-react';
import { validateModel, githubPush, buildApk, type ModelValidation, type GeneratedFilePayload } from './api';

// ── Types ──
export interface DeployFile {
    name: string;
    content: string;
}

interface DeployPanelProps {
    isOpen: boolean;
    onClose: () => void;
    mode: 'web' | 'app' | 'game';
    files: DeployFile[];
    htmlContent: string;
    appName?: string;
    onLog?: (msg: string) => void;
}

type Tab = 'validate' | 'github' | 'export';

// ── Model capability thresholds ──
const STRONG_MODELS = [
    'gpt-4', 'gpt-4o', 'gpt-4-turbo', 'claude-3', 'claude-3.5', 'claude-4',
    'gemini-pro', 'gemini-1.5', 'gemini-2', 'grok-2', 'grok-3',
    'deepseek-coder', 'codestral', 'qwen-2.5-coder'
];

export default function DeployPanel({ isOpen, onClose, mode, files, htmlContent, appName = 'AstraApp', onLog }: DeployPanelProps) {
    const [activeTab, setActiveTab] = useState<Tab>('validate');
    const [modelStatus, setModelStatus] = useState<ModelValidation | null>(null);
    const [isValidating, setIsValidating] = useState(false);

    // GitHub state
    const [repoUrl, setRepoUrl] = useState('');
    const [ghToken, setGhToken] = useState('');
    const [commitMsg, setCommitMsg] = useState('feat: generated by ASTRA Builder');
    const [isPushing, setIsPushing] = useState(false);
    const [pushResult, setPushResult] = useState<{ ok: boolean; msg: string } | null>(null);

    // Export state
    const [isExporting, setIsExporting] = useState(false);
    const [exportResult, setExportResult] = useState<{ ok: boolean; msg: string } | null>(null);

    const log = useCallback((msg: string) => onLog?.(msg), [onLog]);

    // ── Validate model on open ──
    useEffect(() => {
        if (isOpen && !modelStatus) {
            handleValidate();
        }
    }, [isOpen]);

    const handleValidate = async () => {
        setIsValidating(true);
        setModelStatus(null);
        log('🔍 Validating API model eligibility...');
        try {
            const result = await validateModel();
            setModelStatus(result);
            log(result.eligible
                ? `✅ Model "${result.model}" is eligible for full-stack generation`
                : `⚠️ Model "${result.model}" — ${result.reason}`);
        } catch {
            // Fallback: offline mode or backend down
            setModelStatus({
                eligible: false,
                model: 'unknown',
                reason: 'Backend unreachable. Configure a provider API key in Settings to enable AI-powered building.',
                capabilities: []
            });
            log('⚠️ Could not reach backend for model validation');
        }
        setIsValidating(false);
    };

    // ── GitHub Push ──
    const handleGitHubPush = async () => {
        if (!repoUrl.trim() || !ghToken.trim()) return;
        setIsPushing(true);
        setPushResult(null);
        log(`📤 Pushing ${files.length} files to ${repoUrl}...`);
        try {
            const payload: GeneratedFilePayload[] = files.map(f => ({ path: f.name, content: f.content }));
            const res = await githubPush(repoUrl, ghToken, payload, commitMsg);
            setPushResult({ ok: true, msg: res.message || 'Successfully pushed to GitHub!' });
            log(`✅ Pushed to GitHub: ${res.commit_sha?.slice(0, 7) || 'success'}`);
        } catch (err: any) {
            setPushResult({ ok: false, msg: err?.message || 'Push failed' });
            log(`❌ GitHub push failed: ${err?.message}`);
        }
        setIsPushing(false);
    };

    // ── Export (ZIP for web, APK for app/game) ──
    const handleExport = async () => {
        setIsExporting(true);
        setExportResult(null);

        if (mode === 'web') {
            // Client-side ZIP using Blob
            log('📦 Bundling project as ZIP...');
            try {
                // Build a simple ZIP manually using Blob (no dependency needed for single-file)
                const blob = new Blob([htmlContent], { type: 'text/html' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${appName || 'astra-web-app'}.html`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
                setExportResult({ ok: true, msg: 'HTML file downloaded successfully!' });
                log('✅ Web app exported as HTML');
            } catch (err: any) {
                setExportResult({ ok: false, msg: err?.message || 'Export failed' });
                log(`❌ Export failed: ${err?.message}`);
            }
        } else {
            // APK build for app/game
            log('📱 Building APK package...');
            try {
                const res = await buildApk(htmlContent, appName, `com.astra.${appName.toLowerCase().replace(/[^a-z0-9]/g, '')}`);
                if (res.download_url) {
                    window.open(res.download_url, '_blank');
                    setExportResult({ ok: true, msg: `APK ready! Size: ${res.size_mb?.toFixed(1) || '?'}MB` });
                    log(`✅ APK built: ${res.size_mb?.toFixed(1)}MB`);
                } else if (res.apk_base64) {
                    // Direct base64 download
                    const byteChars = atob(res.apk_base64);
                    const byteArray = new Uint8Array(byteChars.length);
                    for (let i = 0; i < byteChars.length; i++) byteArray[i] = byteChars.charCodeAt(i);
                    const blob = new Blob([byteArray], { type: 'application/vnd.android.package-archive' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `${appName}.apk`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    URL.revokeObjectURL(url);
                    setExportResult({ ok: true, msg: 'APK downloaded successfully!' });
                    log('✅ APK downloaded');
                } else {
                    // Fallback: download as HTML
                    const blob = new Blob([htmlContent], { type: 'text/html' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = `${appName}.html`;
                    document.body.appendChild(a);
                    a.click();
                    document.body.removeChild(a);
                    URL.revokeObjectURL(url);
                    setExportResult({ ok: true, msg: 'Exported as HTML (APK builder not configured on server). Install Capacitor for native APK builds.' });
                    log('⚠️ APK builder unavailable — exported as HTML');
                }
            } catch {
                // Fallback: just download HTML
                const blob = new Blob([htmlContent], { type: 'text/html' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${appName}.html`;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
                URL.revokeObjectURL(url);
                setExportResult({ ok: true, msg: 'Exported as HTML (backend offline). Wrap in Capacitor for APK.' });
                log('⚠️ Backend offline — exported as HTML fallback');
            }
        }
        setIsExporting(false);
    };

    if (!isOpen) return null;

    const modeIcon = mode === 'web' ? <Globe className="w-4 h-4" /> : mode === 'app' ? <Smartphone className="w-4 h-4" /> : <Gamepad2 className="w-4 h-4" />;
    const modeLabel = mode === 'web' ? 'Web App' : mode === 'app' ? 'Mobile App' : 'Game';

    return (
        <AnimatePresence>
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
                onClick={onClose}>
                <motion.div initial={{ opacity: 0, scale: 0.95, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} exit={{ opacity: 0, scale: 0.95 }}
                    className="w-full max-w-lg bg-[#0d0d12] border border-white/[0.08] rounded-2xl shadow-2xl overflow-hidden"
                    onClick={e => e.stopPropagation()}>

                    {/* Header */}
                    <div className="flex items-center justify-between px-5 py-4 border-b border-white/[0.06]">
                        <div className="flex items-center gap-2.5">
                            {modeIcon}
                            <span className="font-bold text-sm">Deploy {modeLabel}</span>
                            <span className="text-[9px] font-mono text-white/20 bg-white/[0.04] px-2 py-0.5 rounded">{files.length} files</span>
                        </div>
                        <button onClick={onClose} className="p-1.5 text-white/30 hover:text-white hover:bg-white/5 rounded-lg transition-colors">
                            <X className="w-4 h-4" />
                        </button>
                    </div>

                    {/* Tabs */}
                    <div className="flex border-b border-white/[0.06] px-4">
                        {([
                            { id: 'validate' as Tab, label: 'Model Check', Icon: Shield },
                            { id: 'github' as Tab, label: 'GitHub Push', Icon: Github },
                            { id: 'export' as Tab, label: mode === 'web' ? 'ZIP Export' : 'APK Export', Icon: mode === 'web' ? Download : Package },
                        ]).map(({ id, label, Icon }) => (
                            <button key={id} onClick={() => setActiveTab(id)}
                                className={`px-3 py-2.5 text-[11px] font-bold flex items-center gap-1.5 border-b-2 transition-colors ${activeTab === id ? 'border-violet-500 text-violet-400' : 'border-transparent text-white/30 hover:text-white/50'}`}>
                                <Icon className="w-3.5 h-3.5" /> {label}
                            </button>
                        ))}
                    </div>

                    {/* Content */}
                    <div className="p-5 min-h-[280px]">
                        {/* ── Validate Tab ── */}
                        {activeTab === 'validate' && (
                            <div className="space-y-4">
                                <p className="text-[12px] text-white/40 leading-relaxed">
                                    Checks if your configured API model is powerful enough to generate full-stack {modeLabel.toLowerCase()} code.
                                </p>
                                {isValidating ? (
                                    <div className="flex items-center gap-3 p-4 bg-violet-500/5 border border-violet-500/20 rounded-xl">
                                        <Loader2 className="w-5 h-5 text-violet-400 animate-spin" />
                                        <span className="text-sm text-violet-300">Validating model capabilities...</span>
                                    </div>
                                ) : modelStatus ? (
                                    <div className={`p-4 rounded-xl border ${modelStatus.eligible ? 'bg-emerald-500/5 border-emerald-500/20' : 'bg-amber-500/5 border-amber-500/20'}`}>
                                        <div className="flex items-center gap-2 mb-2">
                                            {modelStatus.eligible
                                                ? <CheckCircle2 className="w-5 h-5 text-emerald-400" />
                                                : <AlertTriangle className="w-5 h-5 text-amber-400" />}
                                            <span className={`font-bold text-sm ${modelStatus.eligible ? 'text-emerald-400' : 'text-amber-400'}`}>
                                                {modelStatus.eligible ? 'Eligible' : 'Limited'}
                                            </span>
                                            <span className="text-[10px] font-mono text-white/20 ml-auto">{modelStatus.model}</span>
                                        </div>
                                        <p className="text-[12px] text-white/50">{modelStatus.reason}</p>
                                        {modelStatus.capabilities && modelStatus.capabilities.length > 0 && (
                                            <div className="flex flex-wrap gap-1.5 mt-3">
                                                {modelStatus.capabilities.map((c, i) => (
                                                    <span key={i} className="text-[9px] font-mono px-2 py-0.5 bg-white/[0.04] border border-white/[0.06] rounded text-white/30">{c}</span>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                ) : null}
                                <button onClick={handleValidate} disabled={isValidating}
                                    className="w-full py-2.5 text-[12px] font-bold bg-white/[0.04] border border-white/[0.08] rounded-xl text-white/50 hover:text-white hover:bg-white/[0.06] transition-colors">
                                    Re-check Model
                                </button>
                            </div>
                        )}

                        {/* ── GitHub Tab ── */}
                        {activeTab === 'github' && (
                            <div className="space-y-4">
                                <div>
                                    <label className="text-[10px] font-bold uppercase tracking-wider text-white/30 mb-1.5 block">Repository URL</label>
                                    <input value={repoUrl} onChange={e => setRepoUrl(e.target.value)}
                                        placeholder="https://github.com/user/repo"
                                        className="w-full px-3 py-2.5 bg-white/[0.04] border border-white/[0.08] rounded-xl text-[13px] text-white placeholder-white/15 outline-none focus:border-violet-500/30" />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold uppercase tracking-wider text-white/30 mb-1.5 flex items-center gap-1">
                                        <Key className="w-2.5 h-2.5" /> GitHub Token
                                    </label>
                                    <input value={ghToken} onChange={e => setGhToken(e.target.value)} type="password"
                                        placeholder="ghp_xxxxxxxxxxxx"
                                        className="w-full px-3 py-2.5 bg-white/[0.04] border border-white/[0.08] rounded-xl text-[13px] text-white placeholder-white/15 outline-none focus:border-violet-500/30 font-mono" />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold uppercase tracking-wider text-white/30 mb-1.5 block">Commit Message</label>
                                    <input value={commitMsg} onChange={e => setCommitMsg(e.target.value)}
                                        className="w-full px-3 py-2.5 bg-white/[0.04] border border-white/[0.08] rounded-xl text-[13px] text-white placeholder-white/15 outline-none focus:border-violet-500/30" />
                                </div>

                                {pushResult && (
                                    <div className={`flex items-center gap-2 p-3 rounded-xl border text-[12px] ${pushResult.ok ? 'bg-emerald-500/5 border-emerald-500/20 text-emerald-400' : 'bg-red-500/5 border-red-500/20 text-red-400'}`}>
                                        {pushResult.ok ? <CheckCircle2 className="w-4 h-4 shrink-0" /> : <XCircle className="w-4 h-4 shrink-0" />}
                                        {pushResult.msg}
                                    </div>
                                )}

                                <button onClick={handleGitHubPush} disabled={isPushing || !repoUrl.trim() || !ghToken.trim()}
                                    className={`w-full py-2.5 rounded-xl text-[12px] font-bold flex items-center justify-center gap-2 transition-all ${!repoUrl.trim() || !ghToken.trim() ? 'bg-white/[0.04] text-white/15' : 'bg-gradient-to-r from-violet-500 to-cyan-500 text-white hover:shadow-[0_0_20px_rgba(139,92,246,0.3)]'}`}>
                                    {isPushing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Github className="w-4 h-4" />}
                                    {isPushing ? 'Pushing...' : 'Push to GitHub'}
                                </button>
                            </div>
                        )}

                        {/* ── Export Tab ── */}
                        {activeTab === 'export' && (
                            <div className="space-y-4">
                                <div className="p-4 bg-white/[0.02] border border-white/[0.06] rounded-xl">
                                    <div className="flex items-center gap-3 mb-3">
                                        {mode === 'web'
                                            ? <Globe className="w-8 h-8 text-violet-400" />
                                            : <Smartphone className="w-8 h-8 text-emerald-400" />}
                                        <div>
                                            <div className="font-bold text-sm">{mode === 'web' ? 'Download HTML' : 'Build APK'}</div>
                                            <div className="text-[11px] text-white/30">
                                                {mode === 'web'
                                                    ? 'Single-file HTML with embedded CSS & JS'
                                                    : 'Android APK wrapped in Capacitor shell'}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-3 text-[10px] text-white/20">
                                        <span>📄 {files.length} files</span>
                                        <span>📦 {(htmlContent.length / 1024).toFixed(1)} KB</span>
                                        <span>🏷️ {appName}</span>
                                    </div>
                                </div>

                                {exportResult && (
                                    <div className={`flex items-start gap-2 p-3 rounded-xl border text-[12px] ${exportResult.ok ? 'bg-emerald-500/5 border-emerald-500/20 text-emerald-300' : 'bg-red-500/5 border-red-500/20 text-red-400'}`}>
                                        {exportResult.ok ? <CheckCircle2 className="w-4 h-4 shrink-0 mt-0.5" /> : <XCircle className="w-4 h-4 shrink-0 mt-0.5" />}
                                        <span>{exportResult.msg}</span>
                                    </div>
                                )}

                                <button onClick={handleExport} disabled={isExporting || !htmlContent}
                                    className={`w-full py-3 rounded-xl text-[13px] font-bold flex items-center justify-center gap-2 transition-all ${!htmlContent ? 'bg-white/[0.04] text-white/15' : mode === 'web' ? 'bg-gradient-to-r from-violet-500 to-cyan-500 text-white hover:shadow-[0_0_20px_rgba(139,92,246,0.3)]' : 'bg-gradient-to-r from-emerald-500 to-teal-500 text-white hover:shadow-[0_0_20px_rgba(16,185,129,0.3)]'}`}>
                                    {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : mode === 'web' ? <Download className="w-4 h-4" /> : <Package className="w-4 h-4" />}
                                    {isExporting ? 'Building...' : mode === 'web' ? 'Download HTML' : 'Build & Download APK'}
                                </button>
                            </div>
                        )}
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}

// ── Compact Model Badge (for embedding in dev page headers) ──
export function ModelBadge({ onLog }: { onLog?: (msg: string) => void }) {
    const [status, setStatus] = useState<ModelValidation | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        validateModel()
            .then(s => { setStatus(s); setLoading(false); onLog?.(s.eligible ? `✅ Model OK: ${s.model}` : `⚠️ Model: ${s.reason}`); })
            .catch(() => { setStatus({ eligible: false, model: 'offline', reason: 'Backend offline', capabilities: [] }); setLoading(false); });
    }, []);

    if (loading) return <div className="w-2 h-2 rounded-full bg-amber-400 animate-pulse" title="Checking model..." />;

    return (
        <div className={`flex items-center gap-1 px-2 py-0.5 rounded text-[9px] font-bold border cursor-default ${status?.eligible ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-amber-500/10 border-amber-500/20 text-amber-400'}`}
            title={status?.reason || ''}>
            {status?.eligible ? <Zap className="w-2.5 h-2.5" /> : <AlertTriangle className="w-2.5 h-2.5" />}
            {status?.model || 'N/A'}
        </div>
    );
}
